# Copyright (C) 2026 Tools-cx-app <localhost.hutao@gmail.com>
# SPDX-License-Identifier: Apache-2.0

inlineHeader = """
Copyright (C) {{props["year"]}} {{props["owner"]}}
SPDX-License-Identifier: Apache-2.0
"""
excludes = [
  ".github/bot/requirements.txt", 
  ".hintrc",
  "libs/",
  "module/libs/"
]

[properties]
year = 2026
owner = "Tools-cx-app <localhost.hutao@gmail.com>"