# Copyright (C) 2026 Tools-cx-app <localhost.hutao@gmail.com>
# SPDX-License-Identifier: Apache-2.0

name: ci-build
on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - "src/**"
      - "Cargo.*"
      - "module/**"
      - "webui/**"
      - "xtask/**"
      - "build.rs"
      - ".github/workflows/ci.yml"
      - ".github/bot/**"
  pull_request:
    branches: ["master"]
    paths:
      - "src/**"
      - "Cargo.*"
      - "module/**"
      - "webui/**"
      - "xtask/**"
      - "build.rs"
      - ".github/workflows/ci.yml"
      - ".github/bot/**"
env:
  CARGO_TERM_COLOR: always
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29
          add-to-path: true
          local-cache: ${{ github.event_name == 'push' }}
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: aarch64-linux-android
          components: rust-src
      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.8
        with:
          cache: ${{ github.event_name == 'push' }}
          cache_dependency_path: webui/pnpm-lock.yaml
          run_install: false
          package_json_file: webui/package.json
      - name: Setup node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "lts/*"
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' }}
      - name: Install build dependencies
        run: |
          cargo install cargo-ndk --locked
      - name: Setup Webui deps
        run: |
          cd webui/
          pnpm install --frozen-lockfile
      - name: Build
        run: |
          cargo xtask build -t arm64
          cargo xtask build -t armv7
      - name: Upload release version
        uses: actions/upload-artifact@v7
        with:
          name: meta-mm-${{ github.run_number }}
          path: output/*.zip
      - name: Upload
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BOT_CI_SESSION: ${{ secrets.BOT_CI_SESSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSIST_TOKEN: ${{ secrets.PERSIST_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          RUN_NO: ${{ github.run_number }}
          RUN_ID: ${{ github.run_id }}
        run: |
          if [ -z "${BOT_TOKEN:-}" ] || [ -z "${CHAT_ID:-}" ] || [ -z "${BOT_CI_SESSION:-}" ]; then
            exit 0
          fi
          pip3 install -r .github/bot/requirements.txt
          python3 .github/bot/bot.py
