# Copyright (C) 2026 Tools-cx-app <localhost.hutao@gmail.com>
# SPDX-License-Identifier: Apache-2.0

name: Manage License Headers

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  license-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Run HawkEye License Check
        uses: korandoru/hawkeye@v6
